- name: shipping setup
  hosts: shipping
  become: yes
  vars:
    mysql_password: RoboShop@1
  tasks:
    - name: Install maven
      ansible.builtin.dnf:
        name: maven
        state: present
    - name: Creating user
      ansible.builtin.user:
        name: roboshop
    - name: Recursively remove directory
      ansible.builtin.file:
        path: /app
        state: absent
    - name: Creating app directory
      ansible.builtin.file:
        path: /app
        state: directory
    - name: Downloading shipping application
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
        dest: /tmp
    - name: Extract shipping application
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes
    - name: Install mvn package
      ansible.builtin.command: mvn clean package
      args:
        chdir: /app
    - name: Rename jar file
      ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
      args:
        chdir: /app
    - name: Copying shipping service file
      ansible.builtin.copy:
        src: shipping.service
        dest: /etc/systemd/system/shipping.service
    - name: Daemon reload
      ansible.builtin.systemd_service:
        daemon_reload: true
    - name: Install mysql client
      ansible.builtin.dnf:
        name: mysql
        state: present
    - name: check cities schema exists or not
      ansible.builtin.command:  mysql -h mysql.techytrees.online -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
      register: schema

    - name: print output
      ansible.builtin.debug:
        msg: "schema output: {{schema}}"

    - name: load cities data
      ansible.builtin.shell: "mysql -h mysql.techytrees.online -uroot -p{{mysql_password}}  < /app/schema/shipping.sql"
      when: schema.stdout != "1"
    - name: start and enable shipping
      ansible.builtin.service:
        name: shipping
        state: restarted
        enabled: yes
    
