- name: setup nginx server
  hosts: web
  become: yes
  tasks:
    - name: stop nginx
      service:
          name: nginx
          state: stopped
    - name: uninstall nginx
      dnf: name=nginx state=absent
