- name: setup nginx server
  hosts: web
  become: yes
  tasks:
    - name: Installing nginx
      dnf: name=nginx state=latest
    - name: Start nginx
      service:
       name: nginx
       state: started
